const config = {
  repositories: [
    {
      name: 'PrestaShop',
      nbRequiredApprovals: 2,
      topwatchersThreshold: 5,
      excludedUsersFromTopwatchers: [
        'prestashop-issue-bot',
        'prestashop-issue-bot[bot]',
        'sentimentbot',
        'sentimentbot[bot]',
        'top-issues',
        'top-issues[bot]',
        'travis-ci',
        'travis-ci[bot]',
        'ps-jarvis',
        'ps-jarvis[bot]',
        'prestonBot',
        'prestonBot[bot]',
        'dependabot',
        'dependabot[bot]',
        'atomiix',
        'eternoendless',
        'jolelievre',
        'kpodemski',
        'matks',
        'matthieu-rolland',
        'NeOMakinG',
        'PierreRambaud',
        'Progi1984',
        'PululuK',
        'sowbiba',
        'khouloudbelguith',
        'Robin-Fischer-PS',
        'MatShir',
        'hibatallahAouadni',
        'florine2623',
        'Julievrz',
        'boubkerbribri',
        'ldeprestashop',
        'marionf',
        'nesrineabdmouleh',
        'prestascott',
        'RomainBocheux',
        'sarahdib',
        'SD1982',
        'TristanLDD',
      ],
      projects: [
        {
          name: 'PrestaShop 1.7.7.6',
          kanbanColumns: {
            // notReadyColumnId: xxxxxxx,
            backlogColumnId: 14540711,
            toBeSpecifiedColumnId: 14540716,
            toDoColumnId: 14540712,
            inProgressColumnId: 14540718,
            toBeReviewedColumnId: 14540720,
            toBeTestedColumnId: 14540726,
            toBerMergedColumnId: 14540727,
            doneColumnId: 14540728,
          },
        },
        {
          name: 'PrestaShop 1.7.8.0',
          kanbanColumns: {
            notReadyColumnId: 7977635,
            backlogColumnId: 6728638,
            toBeSpecifiedColumnId: 7977630,
            toDoColumnId: 6728615,
            inProgressColumnId: 6728616,
            toBeReviewedColumnId: 7309753,
            toBeTestedColumnId: 7309755,
            toBerMergedColumnId: 7309760,
            doneColumnId: 6728617,
          },
        },
      ],
      labels: {
        todo: {name: 'To Do', automatic: true},
        inProgress: {name: 'WIP', automatic: false},
        toBeReproduced: {name: 'TBR', automatic: true},
        toBeSpecified: {name: 'TBS', automatic: true},
        needsMoreInfo: {name: 'NMI', automatic: false},
        toBeTested: {name: 'waiting for QA', automatic: false},
        toBeMerged: {name: 'QA ✔️', automatic: false},
        waitingAuthor: {name: 'waiting for author️', automatic: false},
        fixed: {name: 'Fixed', automatic: true},
        topwatchers: {name: 'Topwatchers', automatic: false},
      },
      milestones: [
        {
          name: '1.7.7.6',
          project: 'PrestaShop 1.7.7.6',
        },
        {
          name: '1.7.8.0',
          project: 'PrestaShop 1.7.8.0',
        },
      ],
    },
  ],
};

module.exports = config;
