const config = {
  repositories: [
    {
      name: 'PrestaShop',
      nbRequiredApprovals: 2,
      topwatchersThreshold: 5,
      excludedUsersFromTopwatchers: [
        'prestashop-issue-bot',
        'prestashop-issue-bot[bot]',
        'sentimentbot',
        'sentimentbot[bot]',
        'top-issues',
        'top-issues[bot]',
        'travis-ci',
        'travis-ci[bot]',
        'ps-jarvis',
        'ps-jarvis[bot]',
        'prestonBot',
        'prestonBot[bot]',
        'dependabot',
        'dependabot[bot]',
        'atomiix',
        'eternoendless',
        'jolelievre',
        'kpodemski',
        'matks',
        'matthieu-rolland',
        'NeOMakinG',
        'PierreRambaud',
        'Progi1984',
        'PululuK',
        'sowbiba',
        'khouloudbelguith',
        'Robin-Fischer-PS',
        'MatShir',
        'hibatallahAouadni',
        'florine2623',
        'Julievrz',
        'boubkerbribri',
        'ldeprestashop',
        'marionf',
        'nesrineabdmouleh',
        'prestascott',
        'RomainBocheux',
        'sarahdib',
        'SD1982',
        'TristanLDD',
      ],
      projects: [
        {
          name: 'PrestaShop 1.7.8.1',
          kanbanColumns: {
            notReadyColumnId: 15345351,
            toDoColumnId: 15345339,
            toBeSpecifiedColumnId: 15345356,
            inProgressColumnId: 15345340,
            toBeReviewedColumnId: 15345357,
            toBeTestedColumnId: 15345369,
            toBeMergedColumnId: 15345366,
            doneColumnId: 15345341,
          },
        },
        {
          name: 'PrestaShop 1.7.8.3',
          kanbanColumns: {
            notReadyColumnId: 16957476,
            toDoColumnId: 16957492,
            toBeSpecifiedColumnId: 16957498,
            inProgressColumnId: 16957477,
            toBeReviewedColumnId: 16957505,
            toBeTestedColumnId: 16957511,
            toBeMergedColumnId: 16957513,
            doneColumnId: 16957478,
          },
        },
        {
          name: 'PrestaShop 8.0.0',
          kanbanColumns: {
            notReadyColumnId: 10578078,
            toDoColumnId: 10578080,
            toBeSpecifiedColumnId: 10578091,
            inProgressColumnId: 10578096,
            toBeReviewedColumnId: 10578098,
            toBeTestedColumnId: 10578100,
            toBeMergedColumnId: 10578102,
            doneColumnId: 10578112,
          },
        },
      ],
      labels: {
        todo: { name: 'To Do', automatic: true },
        ready: { name: 'Ready', automatic: true },
        inAnalysis: { name: 'In analysis', automatic: true },
        inProgress: { name: 'WIP', automatic: true },
        toBeReproduced: { name: 'TBR', automatic: true },
        toBeSpecified: { name: 'TBS', automatic: true },
        needsMoreInfo: { name: 'NMI', automatic: false },
        toBeTested: { name: 'waiting for QA', automatic: false },
        toBeMerged: { name: 'QA ✔️', automatic: false },
        waitingAuthor: { name: 'waiting for author️', automatic: false },
        fixed: { name: 'Fixed', automatic: true },
        topwatchers: { name: 'Topwatchers', automatic: false },
        rejected: { name: 'Rejected', automatic: false },
        blocked: { name: 'Blocked', automatic: true}
      },
      milestones: [
        {
          name: '1.7.8.1',
          project: 'PrestaShop 1.7.8.1',
        },
        {
          name: '1.7.8.3',
          project: 'PrestaShop 1.7.8.3',
        },
        {
          name: '8.0.0',
          project: 'PrestaShop 8.0.0',
        },
      ],
    },
  ],
};

module.exports = config;
