name: IssueBot Production CICD

concurrency:
  group: issuebot-${{ github.ref }}

on:
  release:
    types: [released]

jobs:

  issuebot-production:
    name: Trigger Production CICD
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/tags/')

    steps:

      - name: Get tag
        shell: bash
        id: get_tag
        run: echo TAG=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ISSUEBOT_CD_PAT }}
          repository: ${{ secrets.ISSUEBOT_CD_REPOSITORY }}
          event-type: production_deployment
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ steps.get_tag.outputs.TAG }}"}'
